/** Shared test database schema — mirrors 0001_init.sql */
export const TEST_SCHEMA = `
  CREATE TABLE IF NOT EXISTS secrets (key TEXT PRIMARY KEY, value TEXT NOT NULL, iv TEXT NOT NULL, hmac TEXT NOT NULL DEFAULT '', encrypted_dek TEXT, dek_iv TEXT, description TEXT DEFAULT '', tags TEXT DEFAULT '', expires_at TEXT, created_by TEXT DEFAULT '', updated_by TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')));
  CREATE TABLE IF NOT EXISTS service_tokens (client_id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT DEFAULT '', scopes TEXT DEFAULT '*', role TEXT, created_by TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')), last_used_at TEXT);
  CREATE TABLE IF NOT EXISTS audit_log (id INTEGER PRIMARY KEY AUTOINCREMENT, timestamp TEXT DEFAULT (datetime('now')), method TEXT NOT NULL, identity TEXT NOT NULL, action TEXT NOT NULL, secret_key TEXT, ip TEXT, user_agent TEXT, request_id TEXT, prev_hash TEXT);
  CREATE TABLE IF NOT EXISTS secret_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, secret_key TEXT NOT NULL, value TEXT NOT NULL, iv TEXT NOT NULL, hmac TEXT NOT NULL DEFAULT '', encrypted_dek TEXT, dek_iv TEXT, description TEXT DEFAULT '', changed_by TEXT DEFAULT '', changed_at TEXT DEFAULT (datetime('now')), FOREIGN KEY (secret_key) REFERENCES secrets(key) ON DELETE CASCADE);
  CREATE TABLE IF NOT EXISTS roles (name TEXT PRIMARY KEY, scopes TEXT NOT NULL, allowed_tags TEXT DEFAULT '', description TEXT DEFAULT '', created_by TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')), updated_by TEXT DEFAULT '', updated_at TEXT DEFAULT (datetime('now')));
  CREATE TABLE IF NOT EXISTS users (email TEXT PRIMARY KEY, name TEXT NOT NULL DEFAULT '', role TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, age_public_key TEXT, last_login_at TEXT, created_by TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')), updated_by TEXT DEFAULT '', updated_at TEXT DEFAULT (datetime('now')), FOREIGN KEY (role) REFERENCES roles(name));
  CREATE TABLE IF NOT EXISTS role_policies (id INTEGER PRIMARY KEY AUTOINCREMENT, role TEXT NOT NULL, scopes TEXT NOT NULL, tags TEXT NOT NULL DEFAULT '', description TEXT DEFAULT '', created_by TEXT DEFAULT '', created_at TEXT DEFAULT (datetime('now')), FOREIGN KEY (role) REFERENCES roles(name) ON DELETE CASCADE);
  INSERT OR IGNORE INTO roles (name, scopes, description, created_by) VALUES ('admin', '*', 'Full access', 'system');
`;
